CREATE DATABASE sjryu_egov_study;

CREATE TABLE USER (
	USER_KEY INT PRIMARY KEY,	
	USER_ID VARCHAR(100) NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL,
	USER_PWD INT(20) NOT NULL,
	USER_JOIN_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	USER_MODIFIY_DATE DATETIME,
	USER_STATUS ENUM('active', 'inactive', 'banned') DEFAULT 'active',
	USER_ROLE_TYPE ENUM('user','admin'),
	USER_DELETE_DATE DATETIME 
)

CREATE TABLE BOARD (
	BOARD_KEY INT PRIMARY KEY,
	USER_KEY INT NOT NULL,
	FOREIGN KEY (USER_KEY) REFERENCES USER(USER_KEY),
	BOARD_WRITER VARCHAR(20) NOT NULL,
	BOARD_TITLE VARCHAR(50) NOT NULL,
	BOARD_CONTENT TEXT NOT NULL,
	BOARD_STATU ENUM('draft', 'published', 'hidden', 'deleted') DEFAULT 'draft',
	BOARD_WRITE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	BOARD_MODIFIY_DATE DATETIME,
	BOARD_DELETE_DATE DATETIME
)